ALTER TABLE "User" ADD COLUMN "passwordHash" TEXT;

ALTER TABLE "Project" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Stage" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Message" ADD COLUMN "projectId" TEXT REFERENCES "Project" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

UPDATE "Project" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
